#!/bin/ksh
# script to run CBDCBS standardisation
#
# 2 parameters :
# 1 = country code
# 2 = extraction file / table
#
echo ag_CBDCBS $1 $2 
#
#mac $1 $2
#run convrt
cp ACT/base.smp ACT/0.smp
cp ACT/$1.smp ACT/0.smp
run recov
cp ACT/base.smp ACT/0.smp
#
run_stan CBD
run agit
run agit2
OBJ/agit2 < IN/agit3.in > agit3.out
OBJ/mmergef < IN/mmergef1.in > mmf1.out
OBJ/mmergef < IN/mmergef2.in > mmf2.out
#
run_stan CBS
cp TMP/aninew.fil TMP/anifil.fil
OBJ/mmergef < IN/mmergef99.in > mmf99.out
run agit00
OBJ/mmergef < IN/mmergef11.in > mmf11.out
OBJ/agit < IN/agit_CBS.in > agit_CBS.out
OBJ/mmergef < IN/mmergef3.in > mmf3.out
OBJ/agit2 < IN/agit4.in > agit4.out
OBJ/mmergef < IN/mmergef4.in > mmf4.out
OBJ/agit2 < IN/agit5.in > agit5.out
OBJ/mmergef < IN/mmergef5.in > mmf5.out
#
OBJ/fbsformat < IN/fbsformat.in | sort -k 1.1,1.12 > CBDCBS.out
run rwcopt
#
echo ag_CBDCBS completed
